"""Phase 5: Push branch, create PR with screenshots."""
from __future__ import annotations

from pathlib import Path

from src.config import Config
from src.status import StatusReporter
from src.prompts.review import pr_description_prompt
from src.pipeline.agent import run_agent
from src.repo import git_commit, git_push, create_pr


async def finalize(
    repo_path: str,
    config: Config,
    reporter: StatusReporter,
) -> None:
    """Generate PR description, push branch, create GitHub PR."""
    branch_name = f"auto-build/{config.job_id[:8]}"

    # Generate PR description with the agent
    print("[finalizer] Generating PR description...")
    await run_agent(
        prompt=pr_description_prompt(),
        allowed_tools=["Read", "Write", "Bash", "Grep", "Glob"],
        cwd=repo_path,
        model=config.model,
    )

    # Commit any screenshots and docs that were generated
    git_commit(repo_path, "docs: add build artifacts, screenshots, and reviews")

    # Push
    print(f"[finalizer] Pushing branch {branch_name}...")
    git_push(repo_path, branch_name)

    # Create PR
    pr_body_file = f"{repo_path}/docs/PR_DESCRIPTION.md"
    if not Path(pr_body_file).exists():
        # Fallback if the agent didn't create the file
        Path(pr_body_file).write_text(
            f"## Auto-build from PRD\n\n"
            f"Job ID: `{config.job_id}`\n\n"
            f"This PR was automatically generated by the PRD worker.\n"
        )
        git_commit(repo_path, "docs: add fallback PR description")
        git_push(repo_path, branch_name)

    print("[finalizer] Creating PR...")
    pr_url = create_pr(
        repo_path=repo_path,
        branch_name=branch_name,
        title=f"Auto-build from PRD: {config.job_id[:8]}",
        body_file=pr_body_file,
        base=config.branch,
    )

    # Count total screenshots
    screenshots_dir = Path(repo_path) / "docs" / "screenshots"
    screenshot_count = len(list(screenshots_dir.rglob("*.png"))) if screenshots_dir.exists() else 0

    await reporter.report("pr_created", {
        "pr_url": pr_url,
        "branch": branch_name,
        "screenshots_count": screenshot_count,
    })

    await reporter.report("completed", {
        "pr_url": pr_url,
        "branch": branch_name,
        "screenshots_count": screenshot_count,
    })

    print(f"[finalizer] PR created: {pr_url}")
